### ISSUE TITLE
How are you gonna support localization ? ? 

### ISSUE THREAD

**Issue by markusranda** [Mordi490/mordi490.github.io#5]
https://github.com/Mordi490/mordi490.github.io/blob/3fad1eb36f08945c999dbc9b007b23b7ff9857fd/js/date_time.js#L12

I looked at your code and how you have made yourself an array of hard boiled strings ? ? ? How will you ever mange to get full localization support this way? Anyway keep up the cool work you crazy cat.

Best regards
Team Natron

**Comment by Mordi490** [comment]
The site doesn't need any JS as of right now. All JS files have been dropped.

**Comment by 0us** [comment]
> 
> 
> The site doesn't need any JS as of right now. All JS files have been dropped.

I appreciate the brutally honest response. This is why YOU are the lead of this project.
